### ISSUE TITLE
database files are incompatible with server

### ISSUE THREAD

**Issue by H3npi** [zulip/docker-zulip#123]
Hey together,

i tried the docker-compose script today, sadly the database container is not starting because of this error message:

```
2018-06-07 10:27:39.630 UTC [1] FATAL:  database files are incompatible with server
2018-06-07 10:27:39.630 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 10.4 (Debian 10.4-1.pgdg90+1).
```

Since i cannot find a repo for the zulip-postgres image, i am posting it here.

BR
H3n

**Comment by timabbott** [comment]
@H3npi can you talk a bit more about what you did? It sounds like you somehow did the database initialization that runs when this project starts with one version of `docker-zulip`  and then tried to boot it with another.  

If your Docker server is new, you should be able to just remove `/opt/docker/zulip/` and boot it again.

But I'm very curious as to what sequence of steps you took, since this project should only be using 10.x at this point.

**Comment by H3npi** [comment]
Mhm thanks for the input!

It could be that someone tried to install a docker env earlier this year, and these were just some leftovers from that time. I'll try to figure this out.

BR
H3n

**Comment by zingmars** [comment]
I just ran into this. You were right - basically, you were running the old version of the zulip containers, which used the database image from `quay.io/galexrt/postgres-zulip-tsearchextras:latest` to set up the database.

As I understand, the old galexrt's images are now replaced by ones maintained by Zulip. A way to update from these images to the new ones would be appreciated.

**Comment by galexrt** [comment]
@H3npi @zingmars @parity3 You need to upgrade the files by doing some manual steps.

This assumes that your postgres data is saved at `/opt/docker/zulip/postgresql/data`.

1. Make backup of zulip postgres data dir.
2. Stop all Zulip containers, except the postgres one (e.g. use `docker stop` and not `docker-compose stop`).
3. Run:
```
docker run -d \
      --name postgresnew \
      -e POSTGRES_DB=zulip \
      -e POSTGRES_USER=zulip \
      -e POSTGRES_PASSWORD=zulip \
      -v /opt/docker/zulip/postgresql/new:/var/lib/postgresql/data:rw \
      zulip/zulip-postgresql:latest
```
4. Run:
```
docker exec \
    ZULIP_DATABASE_CONTAINER_NAME pg_dumpall -U postgres | \
    docker exec -i postgresnew psql -U postgres
```
That should run through successfully.
5. Run:
```
docker stop ZULIP_DATABASE_CONTAINER_NAME postgresnew
docker rm postgresnew
```
6. Edit your docker-compose.yaml to use the `zulip/zulip-postgresql:latest` image.
7. Run:
```
mv /opt/docker/zulip/postgresql/data /opt/docker/zulip/postgresql/old
mv /opt/docker/zulip/postgresql/new /opt/docker/zulip/postgresql/data
```
8. Delete the existing pods: `docker-compose rm`
9. Start it up again `docker-compose up`.

To note: the Postgres upgrade is https://github.com/docker-library/postgres/issues/37 not too good in general right, that is why `pg_dump` is used.

**Comment by timabbott** [comment]
@galexrt do you want to submit those instructions as a PR for how to upgrade from older versions of the image?

**Comment by timabbott** [comment]
(I guess it'd be great if one of you folks tested these instructions first)

**Comment by galexrt** [comment]
@timabbott Well that is what I'm waiting for @H3npi @parity3 to test them so I know they fully work so I can as you wrote add a doc page.

**Comment by parity3** [comment]
Thanks for the instructions! I will try them out in the next 48 hours.

**Comment by parity3** [comment]
The database upgrade worked flawlessly. I decided to create the 'new' dir myself before-hand as I'm not familiar with Docker's auto-create directory policies:

    sudo mkdir /opt/docker/zulip/postgresql/new && \
    sudo chown 999 /opt/docker/zulip/postgresql/new && \
    sudo chmod go-rx /opt/docker/zulip/postgresql/new

And for me, `ZULIP_DATABASE_CONTAINER_NAME` was `dockerzulip_database_1`.

I'm still on v1.7.0-1 of the other images. So I will now try to upgrade to v1.8.1.

Thanks for your help!

**Comment by parity3** [comment]
Upgraded to master for now. I decided to do a build instead of using the `quay.io/galexrt/zulip:1.8.1-0` as the image because it feels like that would possibly not be using the new database or lacks some of the structural changes going on with docker-zulip; and also, it's going to be deprecated as of 1.9; but perhaps I was wrong.

As instructed in the readme, I commented out the image directive in `docker-compose.yml`, and set `ZULIP_GIT_REF` as `1.8.1` in `Dockerfile` and unfortunately the build failed in the provision stage complaining about `build_pygments_data` non-zero exit status.. happened on a retry as well so I gave up and built master. Worked. Sorry, I did not save logs.

But so far I think things are working ok, no errors after the db migrations ran; it even managed to pick up my manual certbot certs from before. Hope this helps.

**Comment by zingmars** [comment]
Seems to have worked (but not before sending me a scary email about Tornado not running when I tried to open the page after the restart. Thankfully, it was just a bit slow to start and everything works fine now).

**Comment by H3npi** [comment]
Just wanted to post my solution (a bit late):

The problem was indeed that someone tried to install zulip on the exact same docker host earlier this year. The Solution from @galexrt worked well!

**Comment by timabbott** [comment]
Cool.  @galexrt want to submit a quick PR adding these instructions in the "upgrading" section under a heading "Upgrading from the old galexrt/docker-zulip" or something?
