### ISSUE TITLE
Easily customize Locales

### ISSUE THREAD

**Issue by Dubrzr** [zulip/docker-zulip#168]
Everywhere in the Dockerfile the locale is set to en_US, but this should be an option.

**Comment by timabbott** [comment]
@Dubrzr the Dockerfile installs the `en_US` in the Dockerfile because the default `C` locale is unsufficient to install some Python packages we depend on.  However, the locale set via environment variables in the Dockerfile has has no effect at runtime -- they're just used for building the container image.  

If you'd like to install additional locales in the container, you're welcome to do that by e.g. building a container image based on the based image that does so, but we can't know what additional locales a user might want.  So I don't think there's anything we can readily improve here (correct me if I'm mistaken).
