### ISSUE TITLE
Dockerhub image for 2.0.4-0 reports itself as 2.0.3+git

### ISSUE THREAD

**Issue by sirpengi** [zulip/docker-zulip#201]
Seems the image posted to dockerhub for zulip version 2.0.4 reports itself as version 2.0.3+git. This happens in our production instance (hitting `api/v1/server_settings` says `zulip_version: "2.0.3+git"`). As far as I can tell it's actually operating on the 2.0.4 code, it just seems like the `version.py` file didn't get updated?

You can see the file from the image itself:
```
$ docker run zulip/docker-zulip:2.0.4-0 cat /home/zulip/deployments/current/version.py
ZULIP_VERSION = "2.0.3+git"
LATEST_MAJOR_VERSION = "2.0"
LATEST_RELEASE_VERSION = "2.0.3"
LATEST_RELEASE_ANNOUNCEMENT = "https://blog.zulip.org/2019/03/01/zulip-2-0-released/"

# Bump the minor PROVISION_VERSION to indicate that folks should provision
# only when going from an old version of the code to a newer version. Bump
# the major version to indicate that folks should provision in both
# directions.

# Typically, adding a dependency only requires a minor version bump, and
# removing a dependency requires a major version bump.

PROVISION_VERSION = '34.2'
```

**Comment by timabbott** [comment]
So, this is actually a pretty messy issue.  The actual problem is that the tag for the 2.0.4 release was pushed incorrectly, and the Docker system ignores the release tarballs and just builds from Git. 

As a result, `docker-zulip 2.0.4-0` was actually the commit on master from around the time of 2.0.4.

I'm pushing a commit to release a 2.0.4-1, but I recommend not upgrading from 2.0.4-0 to 2.0.4-1 (it won't work as it's technically a downgrade), and just planning to upgrade to 2.1 when it comes out.
