### ISSUE TITLE
Can't find zcommand.js in folder's structure

### ISSUE THREAD

**Issue by ilyamordasov** [zulip/docker-zulip#291]
`/home/zulip/deployments/current/` doesn't have `static/js/zcommand.js`. I need this one to extends slash commands, if I put my `/static/js/zcommand.js` into `custom_zulip_files` folder it doesn't work

**Comment by timabbott** [comment]
That's expected, because the Docker container contains only the compiled version of assets like JavaScript files -- Docker's whole model is that a container image isn't meant to be hand-edited.

See https://zulip.readthedocs.io/en/latest/production/upgrade-or-modify.html#modifying-zulip for details on how to make a small Zulip fork (you'll want a development environment for fiddling with that sort of thing anyway).
