### ISSUE TITLE
email_events restarts repeatedly

### ISSUE THREAD

**Issue by cmdntd** [zulip/docker-zulip#300]
When I install zulip by docker there are too many pid of email_events. It seems not to stop to complete
Could I wait for it? Or how to fix this?

```
zulip_1      | 2021-05-21 10:29:41,678 INFO success: zulip_events_email_senders entered RUN
NING state, process has stayed up for > than 1 seconds (startsecs)
zulip_1      | 2021-05-21 10:29:58,589 INFO exited: zulip_events_email_senders (exit status
 1; not expected)
zulip_1      | 2021-05-21 10:29:59,300 INFO spawned: 'zulip_events_email_senders' with pid
197
zulip_1      | 2021-05-21 10:30:00,309 INFO success: zulip_events_email_senders entered RUN
NING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by timabbott** [comment]
What's happening here is that process is continuously crashing and then restarting.  The crashes are likely caused by a configuration issue or potentially an OOM issue if your system have minimal memory; you should check its logs to see the actual traceback.

**Comment by WorldsEndless** [comment]
We are having the same issue on our side. Checking the internal logs for info....

**Comment by sp1z** [comment]
Just in case anyone else comes across this, it appears to be to do with not being able to communicate with the specified SMTP server correctly.

Make sure you have the following envs in docker-compose.yaml set correctly:

SECRETS_email_password
SETTING_ZULIP_ADMINISTRATOR
SETTING_EMAIL_HOST
SETTING_EMAIL_HOST_USER
SETTING_EMAIL_PORT
SETTING_EMAIL_USE_SSL
SETTING_EMAIL_USE_TLS

**Comment by bkraul** [comment]
As a sidenote, for me it was the `NOREPLY_EMAIL_ADDRESS` setting. Basically on my email server configuration, the address must exist at least as an alias in order to be used as a sender address. Once I corrected that, it worked like a charm and the issue went away.

**Comment by timabbott** [comment]
We've upgraded the rabbitmq-server version since this report. But probably the root problem may have been unrelated to that version, but instead having to do with hostname configuration -- RabbitMQ can be very finicky about having a real hostname.

For anyone coming across this class of "the processes keep crashing and then being restarted by supervisord" issue, generally you should (1) look at logs (https://zulip.readthedocs.io/en/latest/production/troubleshooting.html) to see why it's failing, which is usually some sort of configuration problem and (2) get help in chat.zulip.org, not this issue tracker, where it's a lot easier to debug efficiently.
