### ISSUE TITLE
Zulip external databases and services, is this possible ?

### ISSUE THREAD

**Issue by oburd** [zulip/docker-zulip#411]
Hello!
We are using EKS and AWS Services like RDS and etc.
I want to know some information:
1) Is this possible to use different(default it zulip) username and database for connection to database ?
2) Is this possible to connect to RDS instance with full-text search because i had an error psycopg2.errors.ConfigFileError: could not open dictionary file "/rdsdbbin/postgres-14.6.R1/share/tsearch_data/en_us.dict": No such file or directory
3) Is this possible to use sqs instead of rabbitmq ?
4) Is possible dont use memcache only redis ? It will be enough redis only ?
Thank you

**Comment by oburd** [comment]
Additional question
Is this possible to deploy behind AWS ALB ?

**Comment by karlstolley** [comment]
@alexmv, might you have answers to these questions?

**Comment by alexmv** [comment]
> * Is this possible to use different(default it zulip) username and database for connection to database ?

See https://zulip.readthedocs.io/en/latest/production/deployment.html#advanced-installer-options

> * Is this possible to connect to RDS instance with full-text search because i had an error psycopg2.errors.ConfigFileError: could not open dictionary file "/rdsdbbin/postgres-14.6.R1/share/tsearch_data/en_us.dict": No such file or directory

See https://zulip.readthedocs.io/en/latest/production/deployment.html#using-zulip-with-amazon-rds-as-the-database

> * Is this possible to use sqs instead of rabbitmq ?

No.  We intentionally do not rely on AWS-only abstractions, because we want folks to be able to deploy in other clouds.

> * Is possible dont use memcache only redis ? It will be enough redis only ?

Not currently.  See https://zulip.readthedocs.io/en/stable/overview/architecture-overview.html#redis

If you have more questions, please pop into our [development community](https://zulip.com/development-community/), which is likely better suited to answering them.
